export const UNIT_TYPES = {
  BATTLESHIP: {
    name: 'Battleship',
    size: 4,
    count: 1,
    terrain: 'water',
    color: 'bg-blue-600',
  },
  DESTROYER: {
    name: 'Destroyer',
    size: 3,
    count: 1,
    terrain: 'water',
    color: 'bg-blue-500',
  },
  SUBMARINE: {
    name: 'Submarine',
    size: 3,
    count: 1,
    terrain: 'water',
    color: 'bg-blue-400',
  },
  CRUISER: {
    name: 'Cruiser',
    size: 2,
    count: 1,
    terrain: 'water',
    color: 'bg-blue-300',
  },
  CARRIER: {
    name: 'Carrier',
    size: 5,
    count: 1,
    terrain: 'water',
    color: 'bg-blue-700',
  },
  BOMBER: {
    name: 'Bomber',
    size: 1,
    count: 2,
    terrain: 'air',
    color: 'bg-gray-400',
  },
  ARTILLERY: {
    name: 'Artillery',
    size: 1,
    count: 2,
    terrain: 'land',
    color: 'bg-green-600',
  },
  INFANTRY: {
    name: 'Infantry',
    size: 1,
    count: 3,
    terrain: 'land',
    color: 'bg-amber-800',
  },
  TANK: {
    name: 'Tank',
    size: 2,
    count: 2,
    terrain: 'land',
    color: 'bg-green-950',
  },
  VEHICLE: {
    name: 'Light Vehicle',
    size: 1,
    count: 1,
    terrain: 'land',
    color: 'bg-amber-800',
  },
  BUNKER: {
    name: 'Bunker',
    size: 1,
    count: 1,
    terrain: 'land',
    color: 'bg-amber-800',
  },
};